name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.7
            name: ubuntu_latest_Python_3_7
            continue-on-error: true
          - os: ubuntu-latest
            python-version: 3.8
            name: ubuntu_latest_Python_3_8
            continue-on-error: true
          - os: ubuntu-latest
            python-version: 3.9
            name: ubuntu_latest_Python_3_9
            continue-on-error: true
          - os: ubuntu-20.04
            python-version: 3.7
            name: ubuntu_20_04_Python_3_7
            continue-on-error: true
          - os: ubuntu-20.04
            python-version: 3.8
            name: ubuntu_20_04_Python_3_8
            continue-on-error: true
          - os: ubuntu-20.04
            python-version: 3.9
            name: ubuntu_20_04_Python_3_9
            continue-on-error: true
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'
        postgresql db: test_db
        postgresql user: test_user
        postgresql password: test_password
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential gcc
    - name: Install packages
      run: make install
    - name: Install Ruff
      run: pip install ruff
    - name: Lint
      run: make lint
    - name: Test with pytest
      run: make test
    - name: Test with pytest
      run: make test
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
    - name: Format with Black
      run: make format
